apiVersion: v1
data:
  DB_HOST: ZGF0YWJhc2UtMS5jbmNhdTBvdWV5MDYudXMtZWFzdC0yLnJkcy5hbWF6b25hd3MuY29t
  DB_NAME: cG9zdGdyZXM=
  DB_PASSWORD: dFpkflB4Z00xN1JOKWM8cUZ3WXc+LjlqSEhvbA==
  DB_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: "2026-06-16T15:35:55Z"
  name: postgres-secret
  namespace: default
  resourceVersion: "3740975"
  uid: c904fa90-75f8-4f59-99c0-938ae73671f7
type: Opaque
