frontend:
  replicas: 2

  image:
    repository: 230026708124.dkr.ecr.us-east-2.amazonaws.com/frontend-service
    tag: v1

course:
  replicas: 1

  image:
    repository: 230026708124.dkr.ecr.us-east-2.amazonaws.com/course-service
    tag: v10

student:
  replicas: 1

  image:
    repository: 230026708124.dkr.ecr.us-east-2.amazonaws.com/student-service
    tag: v1

service:
  port: 80

bluegreen:
  activeColor: blue
